aliyun-oss:
    endpoint: yourEndpoint
    access-key-id: yourAccessKeyId
    access-key-secret: yourAccessKeySecret
    bucket-name: yourBucketName
    bucket-url: yourBucketUrl
    base-path: yourBasePath
autocode:
    web: web/src
    root: /Users/housheng.huang/new_projects/github_projects/gin-vue-admin
    server: server
    module: github.com/flipped-aurora/gin-vue-admin/server
    ai-path: ""
aws-s3:
    bucket: xxxxx-10005608
    region: ap-shanghai
    endpoint: ""
    secret-id: your-secret-id
    secret-key: your-secret-key
    base-url: https://gin.vue.admin
    path-prefix: github.com/flipped-aurora/gin-vue-admin/server
    s3-force-path-style: false
    disable-ssl: false
captcha:
    key-long: 6
    img-width: 240
    img-height: 80
    open-captcha: 0
    open-captcha-timeout: 3600
cloudflare-r2:
    bucket: xxxx0bucket
    base-url: https://gin.vue.admin.com
    path: uploads
    account-id: xxx_account_id
    access-key-id: xxx_key_id
    secret-access-key: xxx_secret_key
cors:
    mode: strict-whitelist
    whitelist:
        - allow-origin: example1.com
          allow-methods: POST, GET
          allow-headers: Content-Type,AccessToken,X-CSRF-Token, Authorization, Token,X-Token,X-User-Id
          expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
          allow-credentials: true
        - allow-origin: example2.com
          allow-methods: GET, POST
          allow-headers: content-type
          expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
          allow-credentials: true
db-list:
    - type: ""
      alias-name: ""
      prefix: ""
      port: ""
      config: ""
      db-name: ""
      username: ""
      password: ""
      path: ""
      engine: ""
      log-mode: ""
      max-idle-conns: 10
      max-open-conns: 100
      singular: false
      log-zap: false
      disable: true
disk-list:
    - mount-point: /
email:
    to: xxx@qq.com
    from: xxx@163.com
    host: smtp.163.com
    secret: xxx
    nickname: test
    port: 465
    is-ssl: true
    is-loginauth: false
excel:
    dir: ./resource/excel/
hua-wei-obs:
    path: you-path
    bucket: you-bucket
    endpoint: you-endpoint
    access-key: you-access-key
    secret-key: you-secret-key
jwt:
    signing-key: d87d0eb0-748d-41f5-8038-0933a3018ce9
    expires-time: 7d
    buffer-time: 1d
    issuer: qmPlus
local:
    path: uploads/file
    store-path: uploads/file
mcp:
    name: GVA_MCP
    version: v1.0.0
    sse_path: /sse
    message_path: /message
    url_prefix: ""
    addr: 8889
    separate: false
minio:
    endpoint: yourEndpoint
    access-key-id: yourAccessKeyId
    access-key-secret: yourAccessKeySecret
    bucket-name: yourBucketName
    use-ssl: false
    base-path: ""
    bucket-url: http://host:9000/yourBucketName
mongo:
    coll: ""
    options: ""
    database: ""
    username: ""
    password: ""
    auth-source: ""
    min-pool-size: 0
    max-pool-size: 100
    socket-timeout-ms: 0
    connect-timeout-ms: 0
    is-zap: false
    hosts:
        - host: ""
          port: ""
mssql:
    prefix: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    path: ""
    engine: ""
    log-mode: ""
    max-idle-conns: 10
    max-open-conns: 100
    singular: false
    log-zap: false
mysql:
    prefix: ""
    port: "3307"
    config: charset=utf8mb4&parseTime=True&loc=Local
    db-name: gva_skitii
    username: gva_skitii_root
    password: 0tENRZHUWS4EDaOs
    path: mysql2.sqlpub.com
    engine: ""
    log-mode: error
    max-idle-conns: 10
    max-open-conns: 100
    singular: false
    log-zap: false
oracle:
    prefix: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    path: ""
    engine: ""
    log-mode: ""
    max-idle-conns: 10
    max-open-conns: 100
    singular: false
    log-zap: false
pgsql:
    prefix: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    path: ""
    engine: ""
    log-mode: ""
    max-idle-conns: 10
    max-open-conns: 100
    singular: false
    log-zap: false
qiniu:
    zone: ZoneHuaDong
    bucket: ""
    img-path: ""
    access-key: ""
    secret-key: ""
    use-https: false
    use-cdn-domains: false
redis:
    name: ""
    addr: 127.0.0.1:6379
    password: ""
    db: 0
    useCluster: false
    clusterAddrs:
        - 172.21.0.3:7000
        - 172.21.0.4:7001
        - 172.21.0.2:7002
redis-list:
    - name: cache
      addr: 127.0.0.1:6379
      password: ""
      db: 0
      useCluster: false
      clusterAddrs:
        - 172.21.0.3:7000
        - 172.21.0.4:7001
        - 172.21.0.2:7002
sqlite:
    prefix: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    path: ""
    engine: ""
    log-mode: ""
    max-idle-conns: 10
    max-open-conns: 100
    singular: false
    log-zap: false
system:
    db-type: mysql
    oss-type: local
    router-prefix: ""
    addr: 8888
    iplimit-count: 15000
    iplimit-time: 3600
    use-multipoint: false
    use-redis: false
    use-mongo: false
    use-strict-auth: false
    disable-auto-migrate: false
tencent-cos:
    bucket: xxxxx-10005608
    region: ap-shanghai
    secret-id: your-secret-id
    secret-key: your-secret-key
    base-url: https://gin.vue.admin
    path-prefix: github.com/flipped-aurora/gin-vue-admin/server
zap:
    level: info
    prefix: '[github.com/flipped-aurora/gin-vue-admin/server]'
    format: console
    director: log
    encode-level: LowercaseColorLevelEncoder
    stacktrace-key: stacktrace
    show-line: true
    log-in-console: true
    retention-day: -1

# Emag API配置
emag:
    api-url: "https://marketplace.emag.ro/api-ui/opportunities/"
    cookie: "mktp_shared_ga=GA1.1.1943145500.1747473078; mktp_ga=GA1.1.1943145500.1747473078; _fbp=fb.1.1747473078661.361829049602904027; _hjSessionUser_5291419=eyJpZCI6IjllMWNiMjM2LTdiZmMtNTU2MS1hNDBjLTdjYzdiYTg0ODU5YSIsImNyZWF0ZWQiOjE3NDc0NzMwNzg5NjEsImV4aXN0aW5nIjp0cnVlfQ==; ltuid=2513633655672537620; EMAGUUID=1747473655-57332272317-97210.963; site_version_11=not_mobile; EMAGVISITOR=a%3A1%3A%7Bs%3A7%3A%22user_id%22%3Bi%3A2513644461082828543%3B%7D; sr=2560x1415; vp=1644x958; loginTooltipShown=1; FPID=FPID2.2.gYuCP3%2BynGSYeKOiO1En6E%2FR6ETtre65YDcuS%2BuRnJ8%3D.1747474196; _tt_enable_cookie=1; _ttp=01JVES9BRQVRYPAW4VZ9YR99DV_.tt.1; _scid=NtM7WLmitzoTGCbec4y_VBro99aTdKmZ; _pin_unauth=dWlkPVpEazFPRGhsTlRrdE1URmtaaTAwTVdNMkxUZzVPVFl0TjJaak4ySTFPVEF5TnpFMA; _hjSessionUser_278704=eyJpZCI6ImNjZDVlYjZlLTAxMTgtNWM2Yi1hMGQwLTkzZTc4MGI3MGMxYSIsImNyZWF0ZWQiOjE3NDc0NzQyNjQxNzksImV4aXN0aW5nIjp0cnVlfQ==; x-hng=lang=zh-CN&domain=marketplace.emag.ro; gdpr_consent_type=1; _pdr_internal=GA1.2.3306260629.1750326439; api_ui_token=MTEwMTk2NDU4NV9xcV9jb206bm9fcGFzcw==; web4_ga=GA1.1.3306260629.1750326439; user_remember=%DB%11b%C5dy%B9%BA%A4%928%CA%A9%3D%ECl%22U%AB%C5%FC%84%B8%BD%9F%D3r%93%E6%5B%B14%7F%24%1C%A5%FA%DC%B9%0A%18%A6%13E%BD7%FF1%E1%19%D1%28%D6%E8A2%94%0B%FB4%BCn_%17%C6%E1%8A%DA%AD%E0%18%7C%B1H%AD%91~%BC%5D%FE%F6%C6%E4t.%F3%5C%CA7%DD%B7%1Du%C4%FC%DA%A6%7C%DD%04.%CB%CD%D9%20NI%CE%85%2C%097B%A2%AB%80%EF%FA%12%7C%AD%1E3%89%C7%E0%CAa%CA%D2%D4%E3Q%04%0B%8E%84x%FC%84%A8V%B4%C6%D6%BD%0F%A1%2B%28%84%02%FC%BC%AC%A3%02%9D%204%E15%B6%F3%A41%1F%E5; pdr_user_id=51f656d02a0b2a470e41bf670ad6a862; user_token=a26b0130945ae6d682c8c70a3b3fafdf; customer_has_orders=0; EMAG_CUSTOMER=109389546; delivery_locality_id=18782; eab1594=a; eab1593=c; eab1595=c; eab1590=d; GKD=%96%CB%AC%E3%A1%B9%AE%BB%92%A9%8D%DB%BC%BF%95%D0%91%AB%8A%A9%97%B5%A4%E5%96%A9%89%AA%9E%A9%B4%C9%BC%BF%AE%95%90%95%96%AA%96%A5%A8%A8; eab1596=b; mktp_visitor_id=2529239261263957632; eab1597=a; eab1599=b; eab1600=b; eab1601=b; eab1603=b; auth-token=eyJ0eXAiOiJKV1QiLCJraWQiOiIxNzA4MzcwMzc0IiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJlTUFHIEF1dGgiLCJhdWQiOiJlTUFHIiwiZXhwIjoxNzY0ODE1MjI0LCJuYmYiOjE3NjM2MDU1NjQsInNjb3BlIjoib3BlbmlkIHVzZXI6aW5mbyB1c2VyOnNlY3VyaXR5IiwiZGlkIjoiIiwicnQiOiI1YTI4NTVlMjAwZGViNDFiMWVlMWI3ZjZiMzc5NjA3M2ZjNzE1ZTNiIiwiY3VzdG9tZXJfaWQiOjEwOTM4OTU0NiwiZW1haWwiOiJza2l0aWkuaEBnbWFpbC5jb20iLCJwIjoiMDc2ODMyNjc2NCIsInBpdiI6MSwidmlkIjoyNTEzNjQ0NDYxMDgyODI4NTQzfQ.Lnr3dYB-xWKCpHFMuNhUJPWjFItYx4xAZ1JqYimJ_KlU2cYiFPgVGFeYfFtZFTQ43j01nlN7P9KEI-zZwqfvHBCqtUH5PJJ6EhtdJOmUgHdA1plGsmKkLP1QyEng5Rhh1Vo9mxRYQdHBmB6JGO6_jjBvQIEAdwFb8dVEG85TaWN9AzWq7PWPS_UeWWD-wOWuQKkP_twL-Z8rw-OTEDjLkS4Et4Dw5Du0HkkdICLO_2RWEWOZ1Ppkzqul91dccYd9Ova7avZOUuPHBVE512w1bLx8ltZKaoK-HB2-Jw7v9N3trCUs26GHYgHFAMPr68PqhURIg0rcd0fuOQ-uxOVShA; eab1605=c; eab1607=b; eab1606=a; eab1608=b; eab1610=b; eab1613=d; eab1614=b; _sctr=1%7C1766246400000; eab1615=a; wp-wpml_current_language=en; eab1616=a; sapi-token=eyJ1c2VyX2lkIjoyNTEzNjQ0NDYxMDgyODI4NTQzLCJ1c2VyX2tleSI6Inc1c1JZc09GWkhuQ3VjSzZ3NUhDc0h4c0swSENpc080V1hyQ2syM0NvUWtTdzQwb3c2akRqc09jWUJmQ3BzT3NXeTBldzV6RGdjSzBIY0t1UXNLXC93cXR4d3JNb3dyWlRDZ1laSFh6Q3M4T2h3NjNDbFY5OXdyTTF3b1RDdU1PeXc3ckRyMkxEamNLM1hzTzd3cTFwYk1LelZTN0NtMUpsIiwibGFuZ19jb2RlX2tleSI6Inc1c1JZc09GWkhuQ3VjSzZ3NUhDc0h4c0swSENpc080S2NLQXc3SER1eElrdzZURHNjT0p3cWc4R0RNMmJNS3d3NVBDdFEzRHRNS3VTY0tDZThLMU5zS2lSTUtIUzhPdEc4S3hXOE9BTWNLWXc1bkN2OE94dzVva1NzS2F3NGJDdlJiRHVTYkRxUlBDbXNLUkFDVTROa1wvQ3NSc0ZIVnpEdkE9PSIsImF1dGhfdG9rZW5fa2V5IjoidzVzUllzT0ZaSG5DdWNLNnc1SENzSHhzSzBIQ2lzTzRLOEtEdzREQ3B3UERpOE8xd3JKZ3c0SUtRa1wvRGxBbkNyRXdndzVcL0RxY08yU2dcL0NxTU9zdzZJT04xXC9EdEZiRHNjT0F3Nk5Xd3JCRGF4WENvOE96Q203RG1zT1V3cmxJTUJ6Q25NT053NVBEZ01PZk9UUERxc09BV25QRHRNS013NHpDbWNPclk4S0Z3N1BEZ2NLK3dyRENnOEtndzdERGtDY2F3NlREZ2hQRGhNSzF3NnhQU0Jva3dxXC9EaXNPRXc1SERwOE9Dd3FQRGw4S2h3cmN6YXNLWXc1SERtRVRDakE9PSIsInV1aWQiOiIxNzQ3NDczNjU1LTU3MzMyMjcyMzE3LTk3MjEwLjk2MyJ9; cart_summary=%7B%22t%22%3A1766972430%2C%22b%22%3A0%2C%22p%22%3A0%2C%22bfc%22%3A0%2C%22line%22%3A%5B%5D%7D; PHPSESSID=d3cnkl8qlfmj8ss74s70au3p71; __gads=ID=70a99e915efb3d39:T=1747474221:RT=1767065262:S=ALNI_MY2wRFIPhejCh3HQfeL4I3Lbjpr9Q; __gpi=UID=000010c488c03f29:T=1747474221:RT=1767065262:S=ALNI_Ma7h7Epct41T6Tr9ffyJBvb4gi_Lg; __eoi=ID=3ad1ae773bbe17f5:T=1763183347:RT=1767065262:S=AA-AfjYLW6ijjbdBtLI_NtzZVvdA; _pdr_session_id=1767065262; FPLC=GHaP4s0%2B1ZPS9kxvlswUJMiDBdXKqTq3z%2BTWuZIikc0OVEaWdMcCxsN5OI%2FkZG6FIQRGojyzYzNdaDtXVUA6Nrg7OG4z9xXe9coi8rS5eLlloQwKton2VUDwV5vBwA%3D%3D; _ScCbts=%5B%22289%3Bchrome.2%3A2%3A5%22%5D; EMAGROSESSID=b6fe63060dfd4a2fe15a4ec447607293; _gcl_au=1.1.1998507301.1763296168.1774533903.1767065477.1767065484; _pdr_view_id=1767065492-83744.849-425584605; _scid_r=Q1M7WLmitzoTGCbec4y_VBro99aTdKmZPnTDCQ; _uetsid=81fab630e52f11f0827e4374a75f6275; _uetvid=936158f0330111f0ad677777f4088756; web4_ga_NQ0CHVH7MU=GS2.1.s1767065261$o300$g1$t1767065511$j41$l0$h643673847; web4_ga_JJCSV4C7C3=GS2.1.s1767065262$o332$g1$t1767065511$j41$l0$h0; _hjSession_5291419=eyJpZCI6ImU1MGQ2Y2E0LTRlZjAtNDI2NS1iM2I2LTE5NDJhMzhhODUyMCIsImMiOjE3NjcwNjg4ODA0MDYsInMiOjAsInIiOjAsInNiIjowLCJzciI6MCwic2UiOjAsImZzIjowLCJzcCI6MX0=; closedTooltips=eca3be44-0352-4415-af8c-a6270cd8d599%2C0f87b953-031c-4768-b705-2f3fd1e90d56%2C0f87b953-031c-4768-b705-2f3fd1e90d56%2Ce04dc5a3-e7fa-4e93-b353-c59222d69351%2Ce04dc5a3-e7fa-4e93-b353-c59222d69351%2Ceca3be44-0352-4415-af8c-a6270cd8d599%2Ce04dc5a3-e7fa-4e93-b353-c59222d69351%2Ce04dc5a3-e7fa-4e93-b353-c59222d69351%2Ce04dc5a3-e7fa-4e93-b353-c59222d69351%2Ce04dc5a3-e7fa-4e93-b353-c59222d69351%2Ceca3be44-0352-4415-af8c-a6270cd8d599%2Ceca3be44-0352-4415-af8c-a6270cd8d599%2Ceca3be44-0352-4415-af8c-a6270cd8d599%2Ce04dc5a3-e7fa-4e93-b353-c59222d69351%2Ce04dc5a3-e7fa-4e93-b353-c59222d69351%2Ce04dc5a3-e7fa-4e93-b353-c59222d69351%2Ce04dc5a3-e7fa-4e93-b353-c59222d69351%2Ce04dc5a3-e7fa-4e93-b353-c59222d69351%2Ceca3be44-0352-4415-af8c-a6270cd8d599%2Ceca3be44-0352-4415-af8c-a6270cd8d599%2Ceca3be44-0352-4415-af8c-a6270cd8d599%2Ceca3be44-0352-4415-af8c-a6270cd8d599%2Ceca3be44-0352-4415-af8c-a6270cd8d599%2Ceca3be44-0352-4415-af8c-a6270cd8d599%2Ce04dc5a3-e7fa-4e93-b353-c59222d69351%2Ce04dc5a3-e7fa-4e93-b353-c59222d69351%2Ceca3be44-0352-4415-af8c-a6270cd8d599%2Ceca3be44-0352-4415-af8c-a6270cd8d599%2Ceca3be44-0352-4415-af8c-a6270cd8d599%2Ce04dc5a3-e7fa-4e93-b353-c59222d69351%2Ce04dc5a3-e7fa-4e93-b353-c59222d69351%2Ce04dc5a3-e7fa-4e93-b353-c59222d69351%2Ce04dc5a3-e7fa-4e93-b353-c59222d69351%2Ce04dc5a3-e7fa-4e93-b353-c59222d69351%2Ce04dc5a3-e7fa-4e93-b353-c59222d69351%2Ce04dc5a3-e7fa-4e93-b353-c59222d69351%2Ce04dc5a3-e7fa-4e93-b353-c59222d69351%2Ce04dc5a3-e7fa-4e93-b353-c59222d69351%2Ceca3be44-0352-4415-af8c-a6270cd8d599%2Ceca3be44-0352-4415-af8c-a6270cd8d599%2Ce04dc5a3-e7fa-4e93-b353-c59222d69351%2Ceca3be44-0352-4415-af8c-a6270cd8d599%2Ceca3be44-0352-4415-af8c-a6270cd8d599%2Ceca3be44-0352-4415-af8c-a6270cd8d599%2Ceca3be44-0352-4415-af8c-a6270cd8d599%2Ce04dc5a3-e7fa-4e93-b353-c59222d69351%2Ce04dc5a3-e7fa-4e93-b353-c59222d69351%2Ce04dc5a3-e7fa-4e93-b353-c59222d69351%2Ce04dc5a3-e7fa-4e93-b353-c59222d69351%2Ceca3be44-0352-4415-af8c-a6270cd8d599%2Ce04dc5a3-e7fa-4e93-b353-c59222d69351%2Ceca3be44-0352-4415-af8c-a6270cd8d599%2Ceca3be44-0352-4415-af8c-a6270cd8d599%2Ce04dc5a3-e7fa-4e93-b353-c59222d69351%2Ceca3be44-0352-4415-af8c-a6270cd8d599%2Ceca3be44-0352-4415-af8c-a6270cd8d599%2Ce04dc5a3-e7fa-4e93-b353-c59222d69351%2Ce04dc5a3-e7fa-4e93-b353-c59222d69351%2Ce04dc5a3-e7fa-4e93-b353-c59222d69351%2Ceca3be44-0352-4415-af8c-a6270cd8d599%2Ceca3be44-0352-4415-af8c-a6270cd8d599%2Ceca3be44-0352-4415-af8c-a6270cd8d599%2Ceca3be44-0352-4415-af8c-a6270cd8d599%2Ce04dc5a3-e7fa-4e93-b353-c59222d69351%2Ce04dc5a3-e7fa-4e93-b353-c59222d69351%2Ce04dc5a3-e7fa-4e93-b353-c59222d69351%2Ce04dc5a3-e7fa-4e93-b353-c59222d69351%2Ce04dc5a3-e7fa-4e93-b353-c59222d69351%2Ceca3be44-0352-4415-af8c-a6270cd8d599%2Ceca3be44-0352-4415-af8c-a6270cd8d599; mktp_ga_7HBKHZ30L4=GS2.1.s1767068879$o598$g1$t1767068964$j60$l0$h0; mktp_shared_ga_BKFM8TTVFS=GS2.1.s1767068879$o598$g1$t1767068964$j60$l0$h0; ttcsid=1767068875510::uo5nZRFnN9hno9ACkb1d.484.1767068967150.0; ttcsid_C456D2MI9NESIEHM3IRG=1767068875507::kz1Pzl_VSS8rx9sB5x4v.63.1767068967150.1"  # Emag Cookie，建议通过环境变量配置
    request-interval: 1.5   # 请求间隔（秒）
    retry-count: 3          # 单次API调用重试次数
    batch-size: 50          # 每批处理数量
    snapshot-day-gap: 15    # 快照日期间隔（天），超过则使用新日期
    max-fail-count: 3       # 最大连续失败次数，超过则标记为 bad_request
